spring:
  profiles:
    active: test

spring.datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bonify
    username: postgres
    password: ""

server:
  port: 8080

---

spring:
  profiles: test
